### ISSUE TITLE
Nuevas features

### ISSUE THREAD

**Issue by ppizarror** [molguin92/MoulinetteClient#1]
Manuel, tras utilizar el software para la corrección tengo las siguientes sugerencias:
1.- Al abrir la carpeta contenedora se puede volver a abrir la última carpeta que se evaluó? Esto tiene dos utilidades:
- Le sirve al alumno para volver a probar su código sin tener que buscarlo.
- Sirve al corregir para no tener que bucear en el pc buscando la carpeta (sobre todo si los archivos están en otra partición).

2.- Se puede añadir algún flag al jar para ver un log del estado de ejecución de la vm? (O de la tarea), sería super útil.

Saludos

**Comment by molguin92** [comment]
1. Listo! Acabo de hacer un push que agrega esta funcionalidad :)
2. Es más complicado, ya que los alumnos podrían descubrir esto y utilizarlo para ver los casos de prueba... voy a pensar una manera de hacerlo

**Comment by ppizarror** [comment]
o tal solo para ver xq no compila, seria bacan tener un diff entre el output y lo esperado. Una manera podría ser algo como

> **java -jar moul... -auth**  _codigo_  **-verbose**

En donde _codigo_ sea un id único para el cuerpo docente (o 1 para cada uno) que luego tu compruebas en el server y retornas un 'verbose'.

Para evitar tener que ingresar cada vez el código podría almacenarse en un archivo como configuración, onda **moulinette.auth** en donde sólo tenga ese código y con eso poder tener permisos especiales

**Comment by molguin92** [comment]
True. Mira, al final lo que voy a hacer es esto, que es más completo aún: voy a implementar un sistema de autentificación completo con U-Cursos (tienen una API). Todos van a tener que iniciar sesión antes de usar la Moulinette por primera vez, y así puedo asignar a los equipos docentes como administradores, y por defecto hacer que la Moulinette imprima output más verbose.

**Comment by ppizarror** [comment]
suena interesante, incluso además para generar estadísticas de uso xD y ver en cual fallan más para poder tener más consideración en esas preguntas

**Comment by jyby** [comment]
Manuel: asegurate que el sistema se puede usar por usario SIN cuenta en U-Cursos, para no depender de la organizacion de U-Cursos (a veces se atrasan) y para poder usar el sistema afuera de la U de Chile...
